version: '3.1'
services:
  app1:
    build: .
    links:
     - redis
    depends_on:
     - redis
  app2:
    build: .
    links:
     - redis
    depends_on:
     - redis
  app3:
    build: .
    links:
     - redis
    depends_on:
     - redis
  app-error:
    build: .
    environment: 
     - getErrors=true
    links:
     - redis
    depends_on:
     - redis   
  redis:
    image: redis:alpine